package Excptionhandling;

public class Main {
    public static void main(String[] args) {
        exception1 ex = new exception1();
        try {
            ex.divide(78, 0);
        } catch (Exception e) {
            System.out.println("array Arithmatic exception");
        }
      int aarr []= {22,4,45,6,7,8,8};

    }
}
